<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace GPBMetadata;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
N
person.prototest"0
Person
name (	
age (
sex (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

